Add two postcard drafts
rust-community/resources pull request #9
Opened 2018-07-28 16:19 UTC by killercup

This renames the original postcard sketch file to now just be "postcard"
and adds two more pages:

- an "organize a meetup" postcard using notes from @skade
- and draft for a WASM postcard (please bikeshed the content)

2018-07-29 09:13 UTC, skade commented
There's a couple of errors on the meetup one:

* "Meeup form"
* "coworking" instead of "co-working"
* "webite" instead of "website"

2018-08-15 11:54 UTC, badboy requested changes
** postcard - Organize a Meetup.pdf**
What @skade says and:

- What font is used? Looks weird on GitHub, when downloaded I don't see any text
- Hack & Tell -> Show & Tell

**postcard - Contribute to Rust.pdf**

- Rustlings moved here: https://github.com/rustlings/rustlings
- https://www.youtube.com/RustVideos works and is shorter!
- Is it community@rust-lang.org (like on the meetup card) or community-team@rust-lang.org? I think both work, but maybe we should use the shorter one all the time.
- What is with the exclamation mark? Can we use the logo?
- the alignment of the stuff after "or start your own" is weird. I know it's kind of a subgroup, but I don't think that looks good

**postcard - Rust + WASM.pdf**

- Why is starters.servo.org on there?
- same youtube link as above
- content needs change (can we ask the rust-wasm group?)


---

I assume the sketch file is the base for all cards?

2018-08-15 13:12 UTC, skade commented
> I assume the sketch file is the base for all cards?

Yes

2018-08-17 11:49 UTC, killercup commented
Updated.

> What font is used? Looks weird on GitHub, when downloaded I don't see any text

Zilla Slab -- how can you not have _that_ font installed, @badboy?

> Hack & Tell

Would actually be a great format :D

> What is with the exclamation mark? Can we use the logo?

What exclamation mark and what logo are you talking about?

> postcard - Rust + WASM.pdf

ping me if you have content :)

2018-08-17 14:37 UTC, badboy commented
> Zilla Slab -- how can you not have that font installed, @badboy?

I .... I don't know.

> Would actually be a great format :D

You run a successful meetup, implement it!

> What exclamation mark and what logo are you talking about?

![](https://tmp.fnordig.de/scr/13c0dff710.png)

2018-08-17 14:42 UTC, badboy commented
With the font installed I can see now: ! == moz://a.

Can we maybe embed the font in the PDF, so the PDF can be shipped to printers without issues?

2018-08-17 14:44 UTC, killercup commented
Let me look into the PDF stuff… it seems weird.

2018-08-20 08:25 UTC, killercup commented
Since we have some very weird problems with the Zilla font (doesn't even print on my machine after reinstalling several times and seeing it correctly in all the PDFs), @badboy and I decided to swap it out for Merriweather. Will update the PR in a few

2018-08-20 11:51 UTC, badboy approved these changes

2018-08-20 12:35 UTC, killercup commented
:shipit: ?

2018-08-20 12:38 UTC, badboy commented
![ship it](https://shipitsquirrel.github.io/images/ship%20it%20squirrel.png)

2018-08-20 12:44 UTC, killercup commented
@badbors r=shipitsquirrel

(I don't have permissions to merge this)

2018-08-20 12:47 UTC, merged

2018-08-20 12:48 UTC, badboy commented
Permission granted. No wait, merged.

2018-08-20 12:55 UTC, Dowwie commented
![embedded_rust_v1](https://user-images.githubusercontent.com/2601236/44341716-bd9b1480-a456-11e8-9788-d9251f271be0.jpg)

2018-08-20 12:58 UTC, Dowwie commented
I saw a request on #rust IRC about the group looking for postcards for embedded rust.  This motivated me to play around a little bit with vector art.  This is a proof of concept.  Thoughts? :)
@killercup @japaric

2018-08-20 13:06 UTC, badboy commented
@Dowwie Thanks for the effort!
The Rust Embedded group already uses the following logo (for stickers):

![](https://github.com/rust-community/resources/raw/gh-pages/sticker/projects/rust-embedded/sticker-cuts.png)

The postcards usually should have some content for people to get informed about the project and with follow-up links for them to get started. We're happy to take input on that (either as text or ready-to-print designs). Please feel free to open a new issue or PR about that.